---
- name: Install Minio
  hosts: ubuntu-server

  vars:
    app_path: /app/minio
    data_dir: /mnt/nfs_share/minio

  tasks:
  - name: Create minio directory
    become: yes
    file:
      path: "{{ item }}"
      state: directory
      owner: devops
      group: devops
      mode: '0775'
    loop:
      - "{{ app_path }}"

  - name: Copy compose file
    copy:
      src: files/minio/
      dest: "{{ app_path }}"

  - name: Update compose file
    replace:
      path: "{{ app_path }}/docker-compose.yaml"
      regexp: 'MINIO_DATA_DIR'
      replace: '{{ data_dir }}'


  - name: Create and start services
    community.docker.docker_compose_v2:
      project_src: "{{ app_path }}"
      files:
      - docker-compose.yaml
    register: output
