---
- name: Install Home Assistant
  hosts: home-assistant

  vars:
    app_path: /app/home-assistant
    data_dir: /mnt/home-assistant

  tasks:
  - name: Create ha directory
    become: yes
    file:
      path: "{{ item }}"
      state: directory
      owner: devops
      group: devops
      mode: '0775'
    loop:
      - "{{ app_path }}"
      - "{{ data_dir }}"

  - name: Copy compose file
    copy:
      src: files/home-assistant/
      dest: "{{ app_path }}"

  - name: Update compose file
    replace:
      path: "{{ app_path }}/docker-compose.yaml"
      regexp: 'HA_CONFIG_DIR'
      replace: '{{ data_dir }}'

  - name: Create and start services
    community.docker.docker_compose_v2:
      project_src: "{{ app_path }}"
      files:
      - docker-compose.yaml
    register: outputs
