---
- name: Install Advlog
  hosts: app-server

  vars:
    app_path: /app/adventurelog
    data_dir: /mnt/adventurelog

  tasks:
    - name: Create AdventureLog directory
      become: yes
      file:
        path: "{{ item }}"
        state: directory
        owner: devops
        group: devops
        mode: '0775'
      loop:
        - "{{ app_path }}"
        - "{{ data_dir }}/pgdata"
        - "{{ data_dir }}/media"

    - name: Mount an NFS volume
      become: yes
      ansible.posix.mount:
        src: 172.16.0.4:/home/devops/nfs_share/adventurelog
        path: /mnt/adventurelog
        opts: rw,sync
        state: mounted
        fstype: nfs

    - name: Copy compose file
      copy:
        src: files/adventurelog/
        dest: "{{ app_path }}"

    - name: Update compose file
      replace:
        path: "{{ app_path }}/docker-compose.yaml"
        regexp: 'ADVENTURELOG_DATA_DIR'
        replace: '{{ data_dir }}'


    - name: Create and start services
      community.docker.docker_compose_v2:
        project_src: "{{ app_path }}"
        files:
        - docker-compose.yaml
      register: output