---
- name: Install Kong
  hosts: kong-server

  tasks:
  - name: Create kong directory
    become: yes
    file:
      path: "{{ item }}"
      state: directory
      owner: devops
      group: devops
      mode: '0775'
    loop:
      - /kong/kong_data
      - /kong/config

  - name: Copy compose file
    copy:
      src: files/kong/docker-compose.yaml
      dest: /kong

  - name: Create and start services
    community.docker.docker_compose_v2:
      project_src: /kong
      files:
      - docker-compose.yaml
    register: output