version: '3.8'

services:
    n8n:
        image: n8nio/n8n:latest
        ports:
            - "5678:5678"
        environment:
            - N8N_BASIC_AUTH_ACTIVE=false
            - N8N_BASIC_AUTH_USER=admin
            - N8N_BASIC_AUTH_PASSWORD=admin
            - N8N_HOST=localhost
            - N8N_PORT=5678
            - N8N_PROTOCOL=http
            - NODE_FUNCTION_ALLOW_BUILTIN=jsdom
            - NODE_FUNCTION_ALLOW_EXTERNAL=jsdom
            - WEBHOOK_URL=https://n8n-automation.guyzsarun.xyz/
        volumes:
            - N8N_DATA_DIR:/home/node/.n8n
        restart: unless-stopped